<a href="https://colab.research.google.com/github/amirthamini/pytorch/blob/main/pyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch


In [3]:
import torch
import numpy as np

In [4]:
tensor_2d=torch.randn(3,4)
tensor_2d

tensor([[ 0.2358,  1.1067, -1.1802, -0.2027],
        [ 0.0291,  1.7567,  0.4535, -0.2670],
        [ 0.4538,  1.3417, -0.5079,  0.3817]])

In [5]:
tensor_3d=torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [6]:
np1=np.random.randn(3,4)
np1

array([[ 0.95865007,  1.13789674, -0.8648862 , -0.16939912],
       [-0.30985315,  0.65142527, -0.38676179,  0.74426954],
       [-1.57398476,  0.13253173,  0.0223388 , -1.14467709]])

In [7]:
##passing array to the tensor [convert array to tensor ]
my_torch=torch.tensor(np1)
my_torch

tensor([[ 0.9587,  1.1379, -0.8649, -0.1694],
        [-0.3099,  0.6514, -0.3868,  0.7443],
        [-1.5740,  0.1325,  0.0223, -1.1447]], dtype=torch.float64)