<a href="https://colab.research.google.com/github/amirthamini/pytorch/blob/main/tensor_math_operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import numpy as np

In [ ]:
#in pytorch everything in the form of array operation will be initalized as torch
#with using torch.tensor([])

In [9]:
tensor_a=torch.tensor([1,2,3,4])
tensor_b=torch.tensor([5,6,7,8])

In [10]:
#addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [13]:
#by default method
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [15]:
#substration
torch.sub(tensor_a,tensor_b)


tensor([-4, -4, -4, -4])

In [17]:
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [18]:
tensor_a*tensor_b

tensor([ 5, 12, 21, 32])

In [19]:
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [21]:
#divison
tensor_b/tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [22]:
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [24]:
#remainder
torch.remainder(tensor_b,tensor_a)


tensor([0, 0, 1, 0])

In [26]:
#exponents
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [30]:
#another way writing longhand
tensor_a.add(tensor_b)
tensor_a.sub(tensor_b)
tensor_a.mul(tensor_b)
tensor_a.div(tensor_b)
tensor_a.remainder(tensor_b)
tensor_a.pow(tensor_b)

tensor([    1,    64,  2187, 65536])