<a href="https://colab.research.google.com/github/amirthamini/pytorch/blob/main/tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch


In [4]:
my_torch=torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
my_torch1=my_torch.reshape(2,5)
my_torch1


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [2]:
import torch
my_torch2=torch.arange(10)
my_torch2


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
import torch
my_torch5=torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
my_torch6=my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [5]:
my_torch5[1]=32
my_torch5

tensor([ 0, 32,  2,  3,  4,  5,  6,  7,  8,  9])

In [6]:
my_torch6

tensor([[ 0, 32,  2,  3,  4],
        [ 5,  6,  7,  8,  9]])

In [7]:
#slice = grap any item
#syntax
my_torch7[:,1] grapping the only 2nd column

In [8]:

my_torch8=my_torch5.reshape(5,2)
my_torch8

tensor([[ 0, 32],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]])

In [9]:
my_torch8[:,1]

tensor([32,  3,  5,  7,  9])

In [10]:
#return the above same as like a column
my_torch8[:,1:]


tensor([[32],
        [ 3],
        [ 5],
        [ 7],
        [ 9]])